import { plainSyncScript } from "@dataunlocker/script";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Script from "next/script";
import DefenderWrapper from "./DefenderWrapper";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script id="dataunlocker" strategy="beforeInteractive">
          {plainSyncScript}
        </Script>
      </head>
      <body className={inter.className}>
        <DefenderWrapper>{children}</DefenderWrapper>
      </body>
    </html>
  );
}
